In [20]:
import pandas as pd
from pathlib import Path

chemin_fichier = Path.cwd() / '../../data/raw/eco.csv'

# 1. Chargement avec tolérance des mauvaises lignes
# on_bad_lines='skip' ignorera silencieusement le dictionnaire de 16 colonnes à partir de la ligne 59
df_eco = pd.read_csv(
    chemin_fichier, 
    na_values='..', 
    encoding='cp1252',
    on_bad_lines='skip' 
)

# 2. Nettoyage de la pollution (Lignes 55 à 58)
# Les vraies données ont toujours un 'Country Code' (ex: BEN). 
# Les lignes de métadonnées auront un NaN ou du texte inutile ici.
# On supprime toutes les lignes où le code pays est manquant.
df_eco = df_eco.dropna(subset=['Country Code'])

# 3. Visualisation (Sanity Check)
print("--- 5 PREMIÈRES LIGNES ---")
display(df_eco.head())

print("\n--- 5 DERNIÈRES LIGNES (Pour vérifier la coupure) ---")
display(df_eco.tail())

print("\n--- STRUCTURE DU DATASET ---")
df_eco.info()
print(df_eco.columns)

--- 5 PREMIÈRES LIGNES ---

,Country Name,Country Code,Series Name,Series Code,2025 [YR2025]
0,Benin,BEN,"Population, total",SP.POP.TOTL,NaN
1,Benin,BEN,Population growth (annual %),SP.POP.GROW,NaN
2,Benin,BEN,Surface area (sq. km),AG.SRF.TOTL.K2,NaN
3,Benin,BEN,Population density (people per sq. km of land ...,EN.POP.DNST,NaN
4,Benin,BEN,Poverty headcount ratio at national poverty li...,SI.POV.NAHC,NaN

--- 5 DERNIÈRES LIGNES (Pour vérifier la coupure) ---

,Country Name,Country Code,Series Name,Series Code,2025 [YR2025]
57,This is the Sustainable Development Goal indic...,https://datacatalog.worldbank.org/public-licen...,NaN,NaN,NaN
58,Close to 1.2 billion hectares of forest are ma...,The Food and Agricultural Organization (FAO) h...,The world and regional aggregate series do not...,https://datacatalog.worldbank.org/public-licen...,NaN
60,As threats to biodiversity mount,the international community is increasingly f...,and habitat conservation is vital for stemmin...,NaN,NaN
61,Protected areas remain the fundamental buildin...,supported by governments and international in...,others by private individuals,companies,communities and faith groups.
62,The Sustainable Development Goals (SDGs) addre...,SDGs include targets 14 and 15 to highlight t...,The data source for this indicator is the Worl...,Restricted use: Please contact the Protected P...,https://datacatalog.worldbank.org/public-licen...

--- STRUCTURE DU DATASET ---
<class 'pandas.core.frame.DataFrame'>
Index: 57 entries, 0 to 62
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   57 non-null     object
 1   Country Code   57 non-null     object
 2   Series Name    56 non-null     object
 3   Series Code    55 non-null     object
 4   2025 [YR2025]  4 non-null      object
dtypes: object(5)
memory usage: 2.7+ KB
Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '2025 [YR2025]'],
      dtype='object')